### فحص ملف (multipart/form-data)
POST https://phishing-detection-backend-l9rr.onrender.com/analyze-file
Content-Type: multipart/form-data

# REST Client سيستخدم الباونداري أوتوماتيكياً
# اكتب السطرين التاليين فقط، واترك كل شيء للبنية التحتية للـ HTTP Client:
file: ./logo_no_background1.png
